### ISSUE TITLE
is thers any reference paper  or something else?

### ISSUE THREAD

**Issue by lianbin** [casper-auto/CasperAuto#1]
In the path_optimizer.cpp , the funtion  fxf、 fyf  etc, there is so many constant ,   is thers any reference paper  or material ？I don't know how they got here。

**Comment by xpharry** [comment]
Hi I re-wrote the optimization function in c++ for my project based on the assignment (originally wrote in Python) from [Coursera: Motion Planning for Self-Driving Cars](https://www.coursera.org/learn/motion-planning-self-driving-cars/home).

The related paper is:

A. Kelly and B. Nagy, “[Reactive Nonholonomic Trajectory Generation via Parametric Optimal Control,](https://journals.sagepub.com/doi/abs/10.1177/02783649030227008?casa_token=1eJaU-j-rQMAAAAA%3AkOxyZCACePcPX12nrkI9ytr-xQC0KY9nZ_TZ4m7ClMuSbHmpA8TOnlmNMDQVxa7-K_9bEtOFm820&)” The International Journal of Robotics Research, vol. 22, no. 7, pp. 583–601, 2003. This paper discusses the math behind generating spirals to desired terminal states.

Other supplement reading can be found at https://www.coursera.org/learn/motion-planning-self-driving-cars/supplement/oK53F/module-7-supplementary-reading
