### ISSUE TITLE
segment fault

### ISSUE THREAD

**Issue by lianbin** [casper-auto/CasperAuto#2]
I try the lattice_planner ,I get error below,  I found that  in the SubspaceMinimization function,the  FreeVariablesIndex.size() is zero,so that  the WZ matrix is empty 。    

lattice_planner_node: /usr/include/eigen3/Eigen/src/Core/Redux.h:413: typename Eigen::internal::traits<T>::Scalar Eigen::DenseBase<Derived>::redux(const Func&) const [with BinaryOp = Eigen::internal::scalar_max_op<double, double>; Derived = Eigen::PartialReduxExpr<const Eigen::CwiseUnaryOp<Eigen::internal::scalar_abs_op<double>, const Eigen::Matrix<double, -1, -1> >, Eigen::internal::member_sum<double>, 0>; typename Eigen::internal::traits<T>::Scalar = double]: Assertion `this->rows()>0 && this->cols()>0 && "you are using an empty matrix"' failed.

**Comment by xpharry** [comment]
My best guess is the Eigen version is not matching... since I cannot reproduce it in my side.
